### ISSUE TITLE
GC Login not working anymore

### ISSUE THREAD

**Issue by jpakusch** [btittelbach/gctools#5]
Hello,
i used your project as base to implement some features on my own.
since a few days, my login is refused.
Since obviously there were changes on the geocaching website, i would like to know if you have issues too.
Thank you very much for your answer.

Greetings, Jan

**Comment by gerw** [comment]
I think I have found the issue. I have already created a pull request.

**Comment by jpakusch** [comment]
Thank you very much for your reply, after all this time with my plugin not working, i just(one week ago) found time to rebuild it from scratch using a completely different Library for it as Background, "pycaching". so i dont need this anymore.

**Comment by btittelbach** [comment]
Thank you gerw!!
